export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FORM_CART = 'REMOVE_FORM_CART';
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_FORM_WISHLIST = 'REMOVE_FORM_WISHLIST';
export const   CAP_NHAT_EMAIL = "CAP_NHAT_EMAIL";
export const   FECTH_CATEGORIES = "FECTH_CATEGORIES";