export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FORM_CART = 'REMOVE_FORM_CART';
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_FORM_WISHLIST = 'REMOVE_FORM_WISHLIST';